"""add user name

Revision ID: 5a921011aaa8
Revises: a059200cccef
Create Date: 2025-12-16 05:18:38.422789+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a921011aaa8"
down_revision: Union[str, None] = "a059200cccef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("name", sa.String(), nullable=False))
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "entity_state")
    op.drop_column("users", "display_name")
    sa.Enum("active", "deleted", name="entitystate").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="entitystate").create(op.get_bind())
    op.add_column("users", sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "entity_state",
            postgresql.ENUM("active", "deleted", name="entitystate", create_type=False),
            server_default=sa.text("'active'::entitystate"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("users", "name")
    op.drop_table("items")
    # ### end Alembic commands ###
