"""remove start_at add slack_notification to todos

Revision ID: bcf54455f64f
Revises: f3af696393fa
Create Date: 2025-12-30 00:08:22.881282+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bcf54455f64f"
down_revision: Union[str, None] = "f3af696393fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("slack_notification", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.drop_column("todos", "start_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("start_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column("todos", "slack_notification")
    # ### end Alembic commands ###
