"""add notification timing preferences to users

Revision ID: 6f1ba468c778
Revises: bcf54455f64f
Create Date: 2025-12-30 16:40:30.850754+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f1ba468c778"
down_revision: Union[str, None] = "bcf54455f64f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("slack_channel_id", sa.String(length=32), nullable=True))
    op.add_column("tags", sa.Column("slack_channel_name", sa.String(length=128), nullable=True))
    op.add_column("todos", sa.Column("notification_timing_override", sa.String(), nullable=True))
    op.add_column("users", sa.Column("notification_timing", sa.String(), nullable=True))
    op.add_column("users", sa.Column("notification_custom_minutes", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notification_custom_minutes")
    op.drop_column("users", "notification_timing")
    op.drop_column("todos", "notification_timing_override")
    op.drop_column("tags", "slack_channel_name")
    op.drop_column("tags", "slack_channel_id")
    # ### end Alembic commands ###
