"""add description field to todos

Revision ID: 3c56b92b4f99
Revises: 2c12d137605b
Create Date: 2025-12-30 17:43:39.320713+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c56b92b4f99"
down_revision: Union[str, None] = "9590a8596c29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "description")
    # ### end Alembic commands ###
