"""add start_at due_at and due_notification_sent to todos

Revision ID: a2a08da44ea2
Revises: 992aa79ed39d
Create Date: 2025-12-29 17:13:04.069566+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2a08da44ea2"
down_revision: Union[str, None] = "992aa79ed39d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("start_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("todos", sa.Column("due_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("todos", sa.Column("due_notification_sent", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "due_notification_sent")
    op.drop_column("todos", "due_at")
    op.drop_column("todos", "start_at")
    # ### end Alembic commands ###
