"""add slack channel fields to tags

Revision ID: e3b8e48402e7
Revises: 6f1ba468c778
Create Date: 2025-12-30 16:40:55.452990+00:00

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e3b8e48402e7"
down_revision: Union[str, None] = "6f1ba468c778"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
