"""add llm conversation messages table

Revision ID: f3af696393fa
Revises: e258a1c74861
Create Date: 2025-12-29 22:46:24.258355+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3af696393fa"
down_revision: Union[str, None] = "e258a1c74861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_conversation_messages",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_conversation_messages_conversation_id"), "llm_conversation_messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_llm_conversation_messages_user_id"), "llm_conversation_messages", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_conversation_messages_user_id"), table_name="llm_conversation_messages")
    op.drop_index(op.f("ix_llm_conversation_messages_conversation_id"), table_name="llm_conversation_messages")
    op.drop_table("llm_conversation_messages")
    # ### end Alembic commands ###
