"""add notification timing override to todos

Revision ID: 9590a8596c29
Revises: e3b8e48402e7
Create Date: 2025-12-30 16:41:04.793420+00:00

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9590a8596c29"
down_revision: Union[str, None] = "e3b8e48402e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
