"""replace clip and video specific metadata columns with jsonb extra_metadata

Revision ID: 587a86d28f28
Revises: 07a7e4093c79
Create Date: 2026-04-08 20:44:57.276545+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "587a86d28f28"
down_revision: Union[str, None] = "07a7e4093c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clips", sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column("clips", "is_full_body")
    op.drop_column("clips", "has_overlay")
    op.drop_column("clips", "max_num_faces")
    op.drop_column("clips", "avg_face_size")
    op.add_column("videos", sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column("videos", "source")
    op.drop_column("videos", "language")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("videos", sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("videos", "extra_metadata")
    op.add_column("clips", sa.Column("avg_face_size", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column("clips", sa.Column("max_num_faces", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("clips", sa.Column("has_overlay", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("clips", sa.Column("is_full_body", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column("clips", "extra_metadata")
    # ### end Alembic commands ###
