"""add timestamp metadata_field and resolution tracking to clip_feedback

Revision ID: 77cf482f0240
Revises: d092860741e4
Create Date: 2026-04-08 17:24:13.277748+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77cf482f0240"
down_revision: Union[str, None] = "d092860741e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clip_feedback", sa.Column("timestamp", sa.Float(), nullable=True))
    op.add_column("clip_feedback", sa.Column("metadata_field", sa.String(), nullable=True))
    op.add_column("clip_feedback", sa.Column("resolved_in_version_id", sa.Integer(), nullable=True))
    op.add_column("clip_feedback", sa.Column("is_resolved", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "clip_feedback", "dataset_versions", ["resolved_in_version_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clip_feedback", type_="foreignkey")
    op.drop_column("clip_feedback", "is_resolved")
    op.drop_column("clip_feedback", "resolved_in_version_id")
    op.drop_column("clip_feedback", "metadata_field")
    op.drop_column("clip_feedback", "timestamp")
    # ### end Alembic commands ###
