/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * fullstack-base
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from './customAxios';
export interface AddMemberRequest {
    user_id: number;
}

export interface BaseEntitySearchResponseTag {
    entities: Tag[];
    metadata: SearchResponseMetadata;
}

export interface BaseEntitySearchResponseUser {
    entities: User[];
    metadata: SearchResponseMetadata;
}

/**
 * Response containing list of Slack channels.
 */
export interface ChannelSearchResponse {
    channels: SlackChannel[];
}

/**
 * Conversation ID for continuity
 */
export type ChatRequestConversationId = string | null;

/**
 * User's IANA timezone (e.g., 'America/New_York'). Used for interpreting time references.
 */
export type ChatRequestTimezone = string | null;

/**
 * Request to send a chat message.
 */
export interface ChatRequest {
    /** The user's message */
    message: string;
    /** Conversation ID for continuity */
    conversation_id?: ChatRequestConversationId;
    /** User's IANA timezone (e.g., 'America/New_York'). Used for interpreting time references. */
    timezone?: ChatRequestTimezone;
}

/**
 * Response from the chat endpoint.
 */
export interface ChatResponse {
    /** The assistant's response */
    response: string;
    /** Conversation ID for follow-up messages */
    conversation_id: string;
}

/**
 * Request body for Google One Tap / Sign-In authentication.
 */
export interface GoogleCredentialRequest {
    credential: string;
}

export type GoogleLoginResponseEmail = string | null;

export type GoogleLoginResponseMessage = string | null;

/**
 * Response from Google login.
 */
export interface GoogleLoginResponse {
    success: boolean;
    email?: GoogleLoginResponseEmail;
    message?: GoogleLoginResponseMessage;
}

export interface HTTPValidationError {
    detail?: ValidationError[];
}

export interface HealthCheckResponse {
    status: string;
}

export type NotificationPreferencesNotificationTiming = string[] | null;

export type NotificationPreferencesNotificationCustomMinutes = number | null;

/**
 * User notification preferences.
 */
export interface NotificationPreferences {
    notification_timing?: NotificationPreferencesNotificationTiming;
    notification_custom_minutes?: NotificationPreferencesNotificationCustomMinutes;
}

export interface SearchResponseMetadata {
    total_count: number;
    limit: number;
    offset: number;
}

export type SlackChannelNumMembers = number | null;

/**
 * Channel information from Slack.
 */
export interface SlackChannel {
    id: string;
    name: string;
    is_private?: boolean;
    num_members?: SlackChannelNumMembers;
}

export type TagIcon = string | null;

export type TagSlackChannelId = string | null;

export type TagSlackChannelName = string | null;

/**
 * Pydantic model for tags.
 */
export interface Tag {
    id: number;
    created_at: string;
    updated_at: string;
    name: string;
    icon?: TagIcon;
    created_by: number;
    members?: AppBlueprintsTagTagMember[];
    slack_channel_id?: TagSlackChannelId;
    slack_channel_name?: TagSlackChannelName;
}

export type TagCreateRequestIcon = string | null;

export type TagCreateRequestCreatedBy = number | null;

export type TagCreateRequestColor = string | null;

export interface TagCreateRequest {
    name: string;
    icon?: TagCreateRequestIcon;
    created_by?: TagCreateRequestCreatedBy;
    color?: TagCreateRequestColor;
}

export type TagUpdateRequestName = string | null;

export type TagUpdateRequestIcon = string | null;

export type TagUpdateRequestSlackChannelId = string | null;

export type TagUpdateRequestSlackChannelName = string | null;

export interface TagUpdateRequest {
    id: number;
    name?: TagUpdateRequestName;
    icon?: TagUpdateRequestIcon;
    slack_channel_id?: TagUpdateRequestSlackChannelId;
    slack_channel_name?: TagUpdateRequestSlackChannelName;
}

export type TodoDescription = string | null;

export type TodoDueAt = string | null;

export type TodoNotificationTimingOverride = string[] | null;

export type TodoRecurrenceRule = string | null;

export type TodoRecurrenceStart = string | null;

export type TodoRecurrenceEnd = string | null;

export type TodoRecurrenceType = 'fixed_schedule' | 'from_completion' | null;

export interface Todo {
    id: number;
    created_at: string;
    updated_at: string;
    user_id: number;
    title: string;
    description?: TodoDescription;
    completed: boolean;
    due_at?: TodoDueAt;
    due_notification_sent?: boolean;
    slack_notification?: boolean;
    notification_timing_override?: TodoNotificationTimingOverride;
    recurrence_rule?: TodoRecurrenceRule;
    recurrence_start?: TodoRecurrenceStart;
    recurrence_end?: TodoRecurrenceEnd;
    recurrence_type?: TodoRecurrenceType;
    tags?: TodoTag[];
}

export type TodoCreateRequestUserId = number | null;

export type TodoCreateRequestDescription = string | null;

export type TodoCreateRequestDueAt = string | null;

export type TodoCreateRequestNotificationTimingOverride = string[] | null;

export type TodoCreateRequestRecurrenceRule = string | null;

export type TodoCreateRequestRecurrenceStart = string | null;

export type TodoCreateRequestRecurrenceEnd = string | null;

export type TodoCreateRequestRecurrenceType = 'fixed_schedule' | 'from_completion' | null;

export interface TodoCreateRequest {
    user_id?: TodoCreateRequestUserId;
    title: string;
    description?: TodoCreateRequestDescription;
    due_at?: TodoCreateRequestDueAt;
    slack_notification?: boolean;
    notification_timing_override?: TodoCreateRequestNotificationTimingOverride;
    recurrence_rule?: TodoCreateRequestRecurrenceRule;
    recurrence_start?: TodoCreateRequestRecurrenceStart;
    recurrence_end?: TodoCreateRequestRecurrenceEnd;
    recurrence_type?: TodoCreateRequestRecurrenceType;
    tag_ids?: number[];
}

export type TodoTagIcon = string | null;

/**
 * Lightweight tag representation for todo responses (without members).
 */
export interface TodoTag {
    id: number;
    created_at: string;
    updated_at: string;
    name: string;
    icon?: TodoTagIcon;
    created_by: number;
}

export type TodoUpdateRequestCompleted = boolean | null;

export type TodoUpdateRequestTitle = string | null;

export type TodoUpdateRequestDescription = string | null;

export type TodoUpdateRequestDueNotificationSent = boolean | null;

export type TodoUpdateRequestDueAt = string | null;

export type TodoUpdateRequestSlackNotification = boolean | null;

export type TodoUpdateRequestNotificationTimingOverride = string[] | null;

export type TodoUpdateRequestRecurrenceRule = string | null;

export type TodoUpdateRequestRecurrenceStart = string | null;

export type TodoUpdateRequestRecurrenceEnd = string | null;

export type TodoUpdateRequestRecurrenceType = 'fixed_schedule' | 'from_completion' | null;

export type TodoUpdateRequestTagIds = number[] | null;

export interface TodoUpdateRequest {
    id: number;
    completed?: TodoUpdateRequestCompleted;
    title?: TodoUpdateRequestTitle;
    description?: TodoUpdateRequestDescription;
    due_notification_sent?: TodoUpdateRequestDueNotificationSent;
    due_at?: TodoUpdateRequestDueAt;
    slack_notification?: TodoUpdateRequestSlackNotification;
    notification_timing_override?: TodoUpdateRequestNotificationTimingOverride;
    recurrence_rule?: TodoUpdateRequestRecurrenceRule;
    recurrence_start?: TodoUpdateRequestRecurrenceStart;
    recurrence_end?: TodoUpdateRequestRecurrenceEnd;
    recurrence_type?: TodoUpdateRequestRecurrenceType;
    tag_ids?: TodoUpdateRequestTagIds;
}

export type ToolsResponseToolsItem = { [key: string]: unknown };

/**
 * Response listing available tools.
 */
export interface ToolsResponse {
    tools: ToolsResponseToolsItem[];
}

export type UpdateNotificationPreferencesRequestNotificationTiming = string[] | null;

export type UpdateNotificationPreferencesRequestNotificationCustomMinutes = number | null;

/**
 * Request to update notification preferences.
 */
export interface UpdateNotificationPreferencesRequest {
    notification_timing?: UpdateNotificationPreferencesRequestNotificationTiming;
    notification_custom_minutes?: UpdateNotificationPreferencesRequestNotificationCustomMinutes;
}

export type UpdatePreferencesRequestColor = string | null;

export interface UpdatePreferencesRequest {
    color?: UpdatePreferencesRequestColor;
}

export type UserNotificationTiming = string[] | null;

export type UserNotificationCustomMinutes = number | null;

export interface User {
    id: number;
    created_at: string;
    updated_at: string;
    email_address: string;
    name: string;
    notification_timing?: UserNotificationTiming;
    notification_custom_minutes?: UserNotificationCustomMinutes;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
    loc: ValidationErrorLocItem[];
    msg: string;
    type: string;
}

export type AppBlueprintsTagTagMemberRole =
    (typeof AppBlueprintsTagTagMemberRole)[keyof typeof AppBlueprintsTagTagMemberRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppBlueprintsTagTagMemberRole = {
    creator: 'creator',
    member: 'member',
} as const;

export type AppBlueprintsTagTagMemberColor = string | null;

/**
 * Pydantic model for tag membership.
 */
export interface AppBlueprintsTagTagMember {
    id: number;
    created_at: string;
    updated_at: string;
    tag_id: number;
    user_id: number;
    role: AppBlueprintsTagTagMemberRole;
    color?: AppBlueprintsTagTagMemberColor;
}

export type SearchSlackChannelsParams = {
    q: string;
};

/**
 * @summary Get Todos
 */
export const getTodos = (signal?: AbortSignal) => {
    return customAxios<unknown>({ url: `/api/gateway/todo/`, method: 'GET', signal });
};

export const getGetTodosQueryKey = () => {
    return [`/api/gateway/todo/`] as const;
};

export const getGetTodosQueryOptions = <
    TData = Awaited<ReturnType<typeof getTodos>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetTodosQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) =>
        getTodos(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getTodos>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>;
export type GetTodosQueryError = unknown;

export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTodos>>,
                    TError,
                    Awaited<ReturnType<typeof getTodos>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTodos>>,
                    TError,
                    Awaited<ReturnType<typeof getTodos>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Todos
 */

export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetTodosQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create Todo
 */
export const createTodo = (todoCreateRequest: TodoCreateRequest, signal?: AbortSignal) => {
    return customAxios<Todo>({
        url: `/api/gateway/todo/`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: todoCreateRequest,
        signal,
    });
};

export const getCreateTodoMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createTodo>>,
        TError,
        { data: TodoCreateRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createTodo>>,
    TError,
    { data: TodoCreateRequest },
    TContext
> => {
    const mutationKey = ['createTodo'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createTodo>>,
        { data: TodoCreateRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createTodo(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof createTodo>>>;
export type CreateTodoMutationBody = TodoCreateRequest;
export type CreateTodoMutationError = HTTPValidationError;

/**
 * @summary Create Todo
 */
export const useCreateTodo = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createTodo>>,
            TError,
            { data: TodoCreateRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createTodo>>,
    TError,
    { data: TodoCreateRequest },
    TContext
> => {
    const mutationOptions = getCreateTodoMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Update Todo
 */
export const updateTodo = (todoId: number, todoUpdateRequest: TodoUpdateRequest) => {
    return customAxios<Todo>({
        url: `/api/gateway/todo/${todoId}`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: todoUpdateRequest,
    });
};

export const getUpdateTodoMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateTodo>>,
        TError,
        { todoId: number; data: TodoUpdateRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateTodo>>,
    TError,
    { todoId: number; data: TodoUpdateRequest },
    TContext
> => {
    const mutationKey = ['updateTodo'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateTodo>>,
        { todoId: number; data: TodoUpdateRequest }
    > = (props) => {
        const { todoId, data } = props ?? {};

        return updateTodo(todoId, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodo>>>;
export type UpdateTodoMutationBody = TodoUpdateRequest;
export type UpdateTodoMutationError = HTTPValidationError;

/**
 * @summary Update Todo
 */
export const useUpdateTodo = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateTodo>>,
            TError,
            { todoId: number; data: TodoUpdateRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateTodo>>,
    TError,
    { todoId: number; data: TodoUpdateRequest },
    TContext
> => {
    const mutationOptions = getUpdateTodoMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Delete Todo
 */
export const deleteTodo = (todoId: number) => {
    return customAxios<Todo>({ url: `/api/gateway/todo/${todoId}`, method: 'DELETE' });
};

export const getDeleteTodoMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteTodo>>,
        TError,
        { todoId: number },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteTodo>>,
    TError,
    { todoId: number },
    TContext
> => {
    const mutationKey = ['deleteTodo'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteTodo>>,
        { todoId: number }
    > = (props) => {
        const { todoId } = props ?? {};

        return deleteTodo(todoId);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodo>>>;

export type DeleteTodoMutationError = HTTPValidationError;

/**
 * @summary Delete Todo
 */
export const useDeleteTodo = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteTodo>>,
            TError,
            { todoId: number },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteTodo>>,
    TError,
    { todoId: number },
    TContext
> => {
    const mutationOptions = getDeleteTodoMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Get all tags the user has access to.
 * @summary Get Tags
 */
export const getTags = (signal?: AbortSignal) => {
    return customAxios<BaseEntitySearchResponseTag>({
        url: `/api/gateway/tag/`,
        method: 'GET',
        signal,
    });
};

export const getGetTagsQueryKey = () => {
    return [`/api/gateway/tag/`] as const;
};

export const getGetTagsQueryOptions = <
    TData = Awaited<ReturnType<typeof getTags>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetTagsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTags>>> = ({ signal }) =>
        getTags(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getTags>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getTags>>>;
export type GetTagsQueryError = unknown;

export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTags>>,
                    TError,
                    Awaited<ReturnType<typeof getTags>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTags>>,
                    TError,
                    Awaited<ReturnType<typeof getTags>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Tags
 */

export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetTagsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Create a new tag. Creator automatically becomes a member with 'creator' role.
 * @summary Create Tag
 */
export const createTag = (tagCreateRequest: TagCreateRequest, signal?: AbortSignal) => {
    return customAxios<Tag>({
        url: `/api/gateway/tag/`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: tagCreateRequest,
        signal,
    });
};

export const getCreateTagMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createTag>>,
        TError,
        { data: TagCreateRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createTag>>,
    TError,
    { data: TagCreateRequest },
    TContext
> => {
    const mutationKey = ['createTag'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createTag>>,
        { data: TagCreateRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createTag(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateTagMutationResult = NonNullable<Awaited<ReturnType<typeof createTag>>>;
export type CreateTagMutationBody = TagCreateRequest;
export type CreateTagMutationError = HTTPValidationError;

/**
 * @summary Create Tag
 */
export const useCreateTag = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createTag>>,
            TError,
            { data: TagCreateRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createTag>>,
    TError,
    { data: TagCreateRequest },
    TContext
> => {
    const mutationOptions = getCreateTagMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Get a specific tag (must be a member).
 * @summary Get Tag
 */
export const getTag = (tagId: number, signal?: AbortSignal) => {
    return customAxios<Tag>({ url: `/api/gateway/tag/${tagId}`, method: 'GET', signal });
};

export const getGetTagQueryKey = (tagId?: number) => {
    return [`/api/gateway/tag/${tagId}`] as const;
};

export const getGetTagQueryOptions = <
    TData = Awaited<ReturnType<typeof getTag>>,
    TError = HTTPValidationError,
>(
    tagId: number,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>>;
    }
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetTagQueryKey(tagId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTag>>> = ({ signal }) =>
        getTag(tagId, signal);

    return { queryKey, queryFn, enabled: !!tagId, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getTag>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTagQueryResult = NonNullable<Awaited<ReturnType<typeof getTag>>>;
export type GetTagQueryError = HTTPValidationError;

export function useGetTag<TData = Awaited<ReturnType<typeof getTag>>, TError = HTTPValidationError>(
    tagId: number,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTag>>,
                    TError,
                    Awaited<ReturnType<typeof getTag>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTag<TData = Awaited<ReturnType<typeof getTag>>, TError = HTTPValidationError>(
    tagId: number,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getTag>>,
                    TError,
                    Awaited<ReturnType<typeof getTag>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTag<TData = Awaited<ReturnType<typeof getTag>>, TError = HTTPValidationError>(
    tagId: number,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Tag
 */

export function useGetTag<TData = Awaited<ReturnType<typeof getTag>>, TError = HTTPValidationError>(
    tagId: number,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetTagQueryOptions(tagId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Update tag properties (name, icon). Only creator can update.
 * @summary Update Tag
 */
export const updateTag = (tagId: number, tagUpdateRequest: TagUpdateRequest) => {
    return customAxios<Tag>({
        url: `/api/gateway/tag/${tagId}`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: tagUpdateRequest,
    });
};

export const getUpdateTagMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateTag>>,
        TError,
        { tagId: number; data: TagUpdateRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateTag>>,
    TError,
    { tagId: number; data: TagUpdateRequest },
    TContext
> => {
    const mutationKey = ['updateTag'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateTag>>,
        { tagId: number; data: TagUpdateRequest }
    > = (props) => {
        const { tagId, data } = props ?? {};

        return updateTag(tagId, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateTagMutationResult = NonNullable<Awaited<ReturnType<typeof updateTag>>>;
export type UpdateTagMutationBody = TagUpdateRequest;
export type UpdateTagMutationError = HTTPValidationError;

/**
 * @summary Update Tag
 */
export const useUpdateTag = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateTag>>,
            TError,
            { tagId: number; data: TagUpdateRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateTag>>,
    TError,
    { tagId: number; data: TagUpdateRequest },
    TContext
> => {
    const mutationOptions = getUpdateTagMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Delete a tag. Only creator can delete.
 * @summary Delete Tag
 */
export const deleteTag = (tagId: number) => {
    return customAxios<Tag>({ url: `/api/gateway/tag/${tagId}`, method: 'DELETE' });
};

export const getDeleteTagMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteTag>>,
        TError,
        { tagId: number },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteTag>>,
    TError,
    { tagId: number },
    TContext
> => {
    const mutationKey = ['deleteTag'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTag>>, { tagId: number }> = (
        props
    ) => {
        const { tagId } = props ?? {};

        return deleteTag(tagId);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTag>>>;

export type DeleteTagMutationError = HTTPValidationError;

/**
 * @summary Delete Tag
 */
export const useDeleteTag = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteTag>>,
            TError,
            { tagId: number },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteTag>>,
    TError,
    { tagId: number },
    TContext
> => {
    const mutationOptions = getDeleteTagMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Share tag with another user. Only existing members can share.
 * @summary Add Tag Member
 */
export const addTagMember = (
    tagId: number,
    addMemberRequest: AddMemberRequest,
    signal?: AbortSignal
) => {
    return customAxios<AppBlueprintsTagTagMember>({
        url: `/api/gateway/tag/${tagId}/members`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: addMemberRequest,
        signal,
    });
};

export const getAddTagMemberMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof addTagMember>>,
        TError,
        { tagId: number; data: AddMemberRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof addTagMember>>,
    TError,
    { tagId: number; data: AddMemberRequest },
    TContext
> => {
    const mutationKey = ['addTagMember'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof addTagMember>>,
        { tagId: number; data: AddMemberRequest }
    > = (props) => {
        const { tagId, data } = props ?? {};

        return addTagMember(tagId, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type AddTagMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addTagMember>>>;
export type AddTagMemberMutationBody = AddMemberRequest;
export type AddTagMemberMutationError = HTTPValidationError;

/**
 * @summary Add Tag Member
 */
export const useAddTagMember = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof addTagMember>>,
            TError,
            { tagId: number; data: AddMemberRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof addTagMember>>,
    TError,
    { tagId: number; data: AddMemberRequest },
    TContext
> => {
    const mutationOptions = getAddTagMemberMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Remove a member from a tag. Creator can remove anyone; members can only leave.
 * @summary Remove Tag Member
 */
export const removeTagMember = (tagId: number, targetUserId: number) => {
    return customAxios<unknown>({
        url: `/api/gateway/tag/${tagId}/members/${targetUserId}`,
        method: 'DELETE',
    });
};

export const getRemoveTagMemberMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof removeTagMember>>,
        TError,
        { tagId: number; targetUserId: number },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof removeTagMember>>,
    TError,
    { tagId: number; targetUserId: number },
    TContext
> => {
    const mutationKey = ['removeTagMember'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof removeTagMember>>,
        { tagId: number; targetUserId: number }
    > = (props) => {
        const { tagId, targetUserId } = props ?? {};

        return removeTagMember(tagId, targetUserId);
    };

    return { mutationFn, ...mutationOptions };
};

export type RemoveTagMemberMutationResult = NonNullable<
    Awaited<ReturnType<typeof removeTagMember>>
>;

export type RemoveTagMemberMutationError = HTTPValidationError;

/**
 * @summary Remove Tag Member
 */
export const useRemoveTagMember = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof removeTagMember>>,
            TError,
            { tagId: number; targetUserId: number },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof removeTagMember>>,
    TError,
    { tagId: number; targetUserId: number },
    TContext
> => {
    const mutationOptions = getRemoveTagMemberMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Update personal preferences for a tag (color).
 * @summary Update My Tag Preferences
 */
export const updateMyTagPreferences = (
    tagId: number,
    updatePreferencesRequest: UpdatePreferencesRequest
) => {
    return customAxios<AppBlueprintsTagTagMember>({
        url: `/api/gateway/tag/${tagId}/my-preferences`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: updatePreferencesRequest,
    });
};

export const getUpdateMyTagPreferencesMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateMyTagPreferences>>,
        TError,
        { tagId: number; data: UpdatePreferencesRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateMyTagPreferences>>,
    TError,
    { tagId: number; data: UpdatePreferencesRequest },
    TContext
> => {
    const mutationKey = ['updateMyTagPreferences'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateMyTagPreferences>>,
        { tagId: number; data: UpdatePreferencesRequest }
    > = (props) => {
        const { tagId, data } = props ?? {};

        return updateMyTagPreferences(tagId, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateMyTagPreferencesMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateMyTagPreferences>>
>;
export type UpdateMyTagPreferencesMutationBody = UpdatePreferencesRequest;
export type UpdateMyTagPreferencesMutationError = HTTPValidationError;

/**
 * @summary Update My Tag Preferences
 */
export const useUpdateMyTagPreferences = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateMyTagPreferences>>,
            TError,
            { tagId: number; data: UpdatePreferencesRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateMyTagPreferences>>,
    TError,
    { tagId: number; data: UpdatePreferencesRequest },
    TContext
> => {
    const mutationOptions = getUpdateMyTagPreferencesMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Get all users for tag sharing UI. Temporary - needs pagination/search.
 * @summary Get All Users
 */
export const getAllUsers = (signal?: AbortSignal) => {
    return customAxios<BaseEntitySearchResponseUser>({
        url: `/api/gateway/tag/users/all`,
        method: 'GET',
        signal,
    });
};

export const getGetAllUsersQueryKey = () => {
    return [`/api/gateway/tag/users/all`] as const;
};

export const getGetAllUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof getAllUsers>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAllUsersQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) =>
        getAllUsers(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAllUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>;
export type GetAllUsersQueryError = unknown;

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAllUsers>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAllUsers>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get All Users
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetAllUsersQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Get the current authenticated user.
 * @summary Get Me
 */
export const getMe = (signal?: AbortSignal) => {
    return customAxios<User>({ url: `/api/gateway/user/me`, method: 'GET', signal });
};

export const getGetMeQueryKey = () => {
    return [`/api/gateway/user/me`] as const;
};

export const getGetMeQueryOptions = <
    TData = Awaited<ReturnType<typeof getMe>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getMe>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = unknown;

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMe>>,
                    TError,
                    Awaited<ReturnType<typeof getMe>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMe>>,
                    TError,
                    Awaited<ReturnType<typeof getMe>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Me
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetMeQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Refresh the current user's access token.

Validates the existing token via UserDependency, generates a new token,
and sets it as an HTTP-only cookie. Use this to extend sessions or
verify authentication status on app load.
 * @summary Refresh Token
 */
export const refreshToken = (signal?: AbortSignal) => {
    return customAxios<User>({ url: `/api/gateway/user/refresh`, method: 'POST', signal });
};

export const getRefreshTokenMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext> => {
    const mutationKey = ['refreshToken'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, void> = () => {
        return refreshToken();
    };

    return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>;

export type RefreshTokenMutationError = unknown;

/**
 * @summary Refresh Token
 */
export const useRefreshToken = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof refreshToken>>,
            TError,
            void,
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof refreshToken>>, TError, void, TContext> => {
    const mutationOptions = getRefreshTokenMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Get the current user's notification preferences.
 * @summary Get Notification Preferences
 */
export const getNotificationPreferences = (signal?: AbortSignal) => {
    return customAxios<NotificationPreferences>({
        url: `/api/gateway/user/me/notification-preferences`,
        method: 'GET',
        signal,
    });
};

export const getGetNotificationPreferencesQueryKey = () => {
    return [`/api/gateway/user/me/notification-preferences`] as const;
};

export const getGetNotificationPreferencesQueryOptions = <
    TData = Awaited<ReturnType<typeof getNotificationPreferences>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getNotificationPreferences>>, TError, TData>
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetNotificationPreferencesQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationPreferences>>> = ({
        signal,
    }) => getNotificationPreferences(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getNotificationPreferences>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetNotificationPreferencesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getNotificationPreferences>>
>;
export type GetNotificationPreferencesQueryError = unknown;

export function useGetNotificationPreferences<
    TData = Awaited<ReturnType<typeof getNotificationPreferences>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getNotificationPreferences>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotificationPreferences>>,
                    TError,
                    Awaited<ReturnType<typeof getNotificationPreferences>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetNotificationPreferences<
    TData = Awaited<ReturnType<typeof getNotificationPreferences>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getNotificationPreferences>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotificationPreferences>>,
                    TError,
                    Awaited<ReturnType<typeof getNotificationPreferences>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetNotificationPreferences<
    TData = Awaited<ReturnType<typeof getNotificationPreferences>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getNotificationPreferences>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Notification Preferences
 */

export function useGetNotificationPreferences<
    TData = Awaited<ReturnType<typeof getNotificationPreferences>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getNotificationPreferences>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetNotificationPreferencesQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Update the current user's notification preferences.
 * @summary Update Notification Preferences
 */
export const updateNotificationPreferences = (
    updateNotificationPreferencesRequest: UpdateNotificationPreferencesRequest
) => {
    return customAxios<NotificationPreferences>({
        url: `/api/gateway/user/me/notification-preferences`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: updateNotificationPreferencesRequest,
    });
};

export const getUpdateNotificationPreferencesMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateNotificationPreferences>>,
        TError,
        { data: UpdateNotificationPreferencesRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateNotificationPreferences>>,
    TError,
    { data: UpdateNotificationPreferencesRequest },
    TContext
> => {
    const mutationKey = ['updateNotificationPreferences'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateNotificationPreferences>>,
        { data: UpdateNotificationPreferencesRequest }
    > = (props) => {
        const { data } = props ?? {};

        return updateNotificationPreferences(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateNotificationPreferencesMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateNotificationPreferences>>
>;
export type UpdateNotificationPreferencesMutationBody = UpdateNotificationPreferencesRequest;
export type UpdateNotificationPreferencesMutationError = HTTPValidationError;

/**
 * @summary Update Notification Preferences
 */
export const useUpdateNotificationPreferences = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateNotificationPreferences>>,
            TError,
            { data: UpdateNotificationPreferencesRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateNotificationPreferences>>,
    TError,
    { data: UpdateNotificationPreferencesRequest },
    TContext
> => {
    const mutationOptions = getUpdateNotificationPreferencesMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Send a message to the todo assistant.

The assistant can help manage todos through natural language:
- "Show me my todos"
- "Create a todo to buy groceries due tomorrow"
- "Mark todo 5 as complete"
- "What's on my plate for this week?"

When creating todos, the system automatically extracts:
- Due dates from phrases like "tomorrow", "next Tuesday"
- Recurrence patterns from phrases like "every week", "daily"
- Relevant tags based on the todo content
 * @summary Chat
 */
export const chat = (chatRequest: ChatRequest, signal?: AbortSignal) => {
    return customAxios<ChatResponse>({
        url: `/api/gateway/chat/`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: chatRequest,
        signal,
    });
};

export const getChatMutationOptions = <TError = HTTPValidationError, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof chat>>,
        TError,
        { data: ChatRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof chat>>,
    TError,
    { data: ChatRequest },
    TContext
> => {
    const mutationKey = ['chat'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof chat>>, { data: ChatRequest }> = (
        props
    ) => {
        const { data } = props ?? {};

        return chat(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type ChatMutationResult = NonNullable<Awaited<ReturnType<typeof chat>>>;
export type ChatMutationBody = ChatRequest;
export type ChatMutationError = HTTPValidationError;

/**
 * @summary Chat
 */
export const useChat = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof chat>>,
            TError,
            { data: ChatRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof chat>>, TError, { data: ChatRequest }, TContext> => {
    const mutationOptions = getChatMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * Get list of available tools for the chat assistant.
 * @summary Get Available Tools
 */
export const getAvailableTools = (signal?: AbortSignal) => {
    return customAxios<ToolsResponse>({ url: `/api/gateway/chat/tools`, method: 'GET', signal });
};

export const getGetAvailableToolsQueryKey = () => {
    return [`/api/gateway/chat/tools`] as const;
};

export const getGetAvailableToolsQueryOptions = <
    TData = Awaited<ReturnType<typeof getAvailableTools>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableTools>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAvailableToolsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailableTools>>> = ({ signal }) =>
        getAvailableTools(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableTools>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAvailableToolsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAvailableTools>>
>;
export type GetAvailableToolsQueryError = unknown;

export function useGetAvailableTools<
    TData = Awaited<ReturnType<typeof getAvailableTools>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAvailableTools>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAvailableTools>>,
                    TError,
                    Awaited<ReturnType<typeof getAvailableTools>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAvailableTools<
    TData = Awaited<ReturnType<typeof getAvailableTools>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAvailableTools>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAvailableTools>>,
                    TError,
                    Awaited<ReturnType<typeof getAvailableTools>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAvailableTools<
    TData = Awaited<ReturnType<typeof getAvailableTools>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAvailableTools>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Available Tools
 */

export function useGetAvailableTools<
    TData = Awaited<ReturnType<typeof getAvailableTools>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAvailableTools>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetAvailableToolsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Search for Slack channels by name.

Args:
    q: Search query to match against channel names

Returns:
    List of matching Slack channels
 * @summary Search Slack Channels
 */
export const searchSlackChannels = (params: SearchSlackChannelsParams, signal?: AbortSignal) => {
    return customAxios<ChannelSearchResponse>({
        url: `/api/gateway/slack/channels/search`,
        method: 'GET',
        params,
        signal,
    });
};

export const getSearchSlackChannelsQueryKey = (params?: SearchSlackChannelsParams) => {
    return [`/api/gateway/slack/channels/search`, ...(params ? [params] : [])] as const;
};

export const getSearchSlackChannelsQueryOptions = <
    TData = Awaited<ReturnType<typeof searchSlackChannels>>,
    TError = HTTPValidationError,
>(
    params: SearchSlackChannelsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof searchSlackChannels>>, TError, TData>
        >;
    }
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchSlackChannelsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSlackChannels>>> = ({ signal }) =>
        searchSlackChannels(params, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof searchSlackChannels>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type SearchSlackChannelsQueryResult = NonNullable<
    Awaited<ReturnType<typeof searchSlackChannels>>
>;
export type SearchSlackChannelsQueryError = HTTPValidationError;

export function useSearchSlackChannels<
    TData = Awaited<ReturnType<typeof searchSlackChannels>>,
    TError = HTTPValidationError,
>(
    params: SearchSlackChannelsParams,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof searchSlackChannels>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchSlackChannels>>,
                    TError,
                    Awaited<ReturnType<typeof searchSlackChannels>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSearchSlackChannels<
    TData = Awaited<ReturnType<typeof searchSlackChannels>>,
    TError = HTTPValidationError,
>(
    params: SearchSlackChannelsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof searchSlackChannels>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchSlackChannels>>,
                    TError,
                    Awaited<ReturnType<typeof searchSlackChannels>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSearchSlackChannels<
    TData = Awaited<ReturnType<typeof searchSlackChannels>>,
    TError = HTTPValidationError,
>(
    params: SearchSlackChannelsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof searchSlackChannels>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Search Slack Channels
 */

export function useSearchSlackChannels<
    TData = Awaited<ReturnType<typeof searchSlackChannels>>,
    TError = HTTPValidationError,
>(
    params: SearchSlackChannelsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof searchSlackChannels>>, TError, TData>
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getSearchSlackChannelsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Authenticate a user with a Google ID token from Google One Tap / Sign-In.

The credential is a JWT ID token that needs to be verified with Google.
Creates a new user if they don't exist, then sets auth cookie.
 * @summary Google Login
 */
export const googleLogin = (
    googleCredentialRequest: GoogleCredentialRequest,
    signal?: AbortSignal
) => {
    return customAxios<GoogleLoginResponse>({
        url: `/api/gateway/authentication/google/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: googleCredentialRequest,
        signal,
    });
};

export const getGoogleLoginMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof googleLogin>>,
        TError,
        { data: GoogleCredentialRequest },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof googleLogin>>,
    TError,
    { data: GoogleCredentialRequest },
    TContext
> => {
    const mutationKey = ['googleLogin'];
    const { mutation: mutationOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof googleLogin>>,
        { data: GoogleCredentialRequest }
    > = (props) => {
        const { data } = props ?? {};

        return googleLogin(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type GoogleLoginMutationResult = NonNullable<Awaited<ReturnType<typeof googleLogin>>>;
export type GoogleLoginMutationBody = GoogleCredentialRequest;
export type GoogleLoginMutationError = HTTPValidationError;

/**
 * @summary Google Login
 */
export const useGoogleLogin = <TError = HTTPValidationError, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof googleLogin>>,
            TError,
            { data: GoogleCredentialRequest },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof googleLogin>>,
    TError,
    { data: GoogleCredentialRequest },
    TContext
> => {
    const mutationOptions = getGoogleLoginMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Health Check
 */
export const healthCheck = (signal?: AbortSignal) => {
    return customAxios<HealthCheckResponse>({ url: `/health`, method: 'GET', signal });
};

export const getHealthCheckQueryKey = () => {
    return [`/health`] as const;
};

export const getHealthCheckQueryOptions = <
    TData = Awaited<ReturnType<typeof healthCheck>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) =>
        healthCheck(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof healthCheck>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>;
export type HealthCheckQueryError = unknown;

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof healthCheck>>,
                    TError,
                    Awaited<ReturnType<typeof healthCheck>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof healthCheck>>,
                    TError,
                    Awaited<ReturnType<typeof healthCheck>>
                >,
                'initialData'
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Health Check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getHealthCheckQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}
